-- PlanIt baseline schema (Flyway V1).
-- 현재 JPA 엔티티에서 생성된 스키마를 pg_dump 로 추출한 것.

\restrict bFIgHkIwqMiTczcIgn6GRvrzkP35suguKLvHV9YN4E1VYUf7SWJZp9DSUj1ozFO
CREATE TABLE public.completion_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    event_type character varying(30) NOT NULL,
    sprout_delta integer NOT NULL,
    daily_plan_item_id bigint NOT NULL,
    CONSTRAINT completion_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['ITEM_CHECKED'::character varying, 'ITEM_UNCHECKED'::character varying, 'PLAN_COMPLETED'::character varying])::text[])))
);
ALTER TABLE public.completion_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.completion_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.daily_plan_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    end_unit integer NOT NULL,
    estimated_minutes integer NOT NULL,
    manually_adjusted boolean NOT NULL,
    planned_units integer NOT NULL,
    priority character varying(20) NOT NULL,
    range_text_snapshot character varying(500) NOT NULL,
    start_unit integer NOT NULL,
    status character varying(20) NOT NULL,
    study_method_snapshot character varying(255) NOT NULL,
    subject_name_snapshot character varying(50) NOT NULL,
    daily_plan_id bigint NOT NULL,
    subject_scope_id bigint NOT NULL,
    CONSTRAINT daily_plan_items_priority_check CHECK (((priority)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[]))),
    CONSTRAINT daily_plan_items_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);
ALTER TABLE public.daily_plan_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_plan_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.daily_plans (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    plan_date date NOT NULL,
    status character varying(20) NOT NULL,
    exam_plan_id bigint NOT NULL,
    CONSTRAINT daily_plans_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);
ALTER TABLE public.daily_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.event_publication (
    id uuid NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255) NOT NULL,
    listener_id character varying(255) NOT NULL,
    publication_date timestamp(6) with time zone NOT NULL,
    serialized_event character varying(255) NOT NULL
);
CREATE TABLE public.exam_plans (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    exam_date date NOT NULL,
    status character varying(30) NOT NULL,
    target_exam_label character varying(80) NOT NULL,
    target_exam_type character varying(30) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT exam_plans_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT exam_plans_target_exam_type_check CHECK (((target_exam_type)::text = ANY ((ARRAY['SCHOOL_EXAM'::character varying, 'MOCK_EXAM'::character varying, 'CSAT'::character varying, 'CERTIFICATE'::character varying, 'ETC'::character varying])::text[])))
);
ALTER TABLE public.exam_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.notification_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    daily_reminder_enabled boolean NOT NULL,
    daily_reminder_time time(6) without time zone,
    user_id bigint NOT NULL
);
ALTER TABLE public.notification_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.plan_generation_jobs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    generated_plan_id bigint,
    job_id character varying(40) NOT NULL,
    message character varying(255) NOT NULL,
    plan_date date,
    progress_percent integer NOT NULL,
    status character varying(20) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT plan_generation_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);
ALTER TABLE public.plan_generation_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_generation_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token_id character varying(64) NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.study_profiles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    preferred_study_method character varying(30) NOT NULL,
    usual_study_hours_per_day integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT study_profiles_preferred_study_method_check CHECK (((preferred_study_method)::text = ANY ((ARRAY['CONCEPT_FIRST'::character varying, 'PROBLEM_FIRST'::character varying, 'BALANCED'::character varying])::text[])))
);
ALTER TABLE public.study_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.study_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.subject_scopes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    difficulty character varying(20) NOT NULL,
    preferred_method_note character varying(255) NOT NULL,
    raw_range_text character varying(500) NOT NULL,
    remaining_units integer NOT NULL,
    subject_name character varying(50) NOT NULL,
    total_units integer NOT NULL,
    unit_type character varying(20) NOT NULL,
    exam_plan_id bigint NOT NULL,
    CONSTRAINT subject_scopes_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT subject_scopes_unit_type_check CHECK (((unit_type)::text = ANY ((ARRAY['CHAPTER'::character varying, 'PAGE'::character varying, 'QUESTION'::character varying, 'PASSAGE'::character varying, 'TOPIC'::character varying, 'CUSTOM'::character varying])::text[])))
);
ALTER TABLE public.subject_scopes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_scopes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.user_accounts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(120) NOT NULL,
    name character varying(50) NOT NULL,
    onboarding_completed boolean NOT NULL,
    password_hash character varying(255) NOT NULL
);
ALTER TABLE public.user_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.completion_events
    ADD CONSTRAINT completion_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.daily_plan_items
    ADD CONSTRAINT daily_plan_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.daily_plans
    ADD CONSTRAINT daily_plans_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.event_publication
    ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.exam_plans
    ADD CONSTRAINT exam_plans_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT notification_settings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.plan_generation_jobs
    ADD CONSTRAINT plan_generation_jobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.study_profiles
    ADD CONSTRAINT study_profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subject_scopes
    ADD CONSTRAINT subject_scopes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.plan_generation_jobs
    ADD CONSTRAINT uk4743ilp48yd0whvasm3k88w3t UNIQUE (job_id);
ALTER TABLE ONLY public.study_profiles
    ADD CONSTRAINT uk4g5tdout9k78q7mf1wip6khpb UNIQUE (user_id);
ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT ukf9sl209luxhu4rylls0h1m625 UNIQUE (email);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukkt71wnjd35heo0p6pewmrdf5f UNIQUE (token_id);
ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT ukm9ggfvif86mvq5382j88cequn UNIQUE (user_id);
ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT user_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.daily_plan_items
    ADD CONSTRAINT fk3d7n5pvx60sv9ek2nasyg4u3r FOREIGN KEY (daily_plan_id) REFERENCES public.daily_plans(id);
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk4ma0jg35fmwwfv2wrr2npjvu8 FOREIGN KEY (user_id) REFERENCES public.user_accounts(id);
ALTER TABLE ONLY public.plan_generation_jobs
    ADD CONSTRAINT fk4swubw6mec9upti18wp28vlvd FOREIGN KEY (user_id) REFERENCES public.user_accounts(id);
ALTER TABLE ONLY public.completion_events
    ADD CONSTRAINT fk5n199scrgn2tvrpifp23nv96r FOREIGN KEY (daily_plan_item_id) REFERENCES public.daily_plan_items(id);
ALTER TABLE ONLY public.daily_plans
    ADD CONSTRAINT fk6d1fxjkn46fjmplnvlmvhn8u9 FOREIGN KEY (exam_plan_id) REFERENCES public.exam_plans(id);
ALTER TABLE ONLY public.exam_plans
    ADD CONSTRAINT fk8f8q5sth7c06q5ppiu20ifwox FOREIGN KEY (user_id) REFERENCES public.user_accounts(id);
ALTER TABLE ONLY public.study_profiles
    ADD CONSTRAINT fkbt0tmi5o6y04x8wkdv8yvc0td FOREIGN KEY (user_id) REFERENCES public.user_accounts(id);
ALTER TABLE ONLY public.subject_scopes
    ADD CONSTRAINT fkkdfb5wphpq6tuk9lft6gol0rs FOREIGN KEY (exam_plan_id) REFERENCES public.exam_plans(id);
ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT fkm745sd1qn9xivusbd1u2iab1i FOREIGN KEY (user_id) REFERENCES public.user_accounts(id);
ALTER TABLE ONLY public.daily_plan_items
    ADD CONSTRAINT fknva2op8hv2iqqkw0n5ddghc7e FOREIGN KEY (subject_scope_id) REFERENCES public.subject_scopes(id);
\unrestrict bFIgHkIwqMiTczcIgn6GRvrzkP35suguKLvHV9YN4E1VYUf7SWJZp9DSUj1ozFO
